### ISSUE TITLE
DefaultPropertySchemaの制約で、任意のInterpreterが使えるようにしてほしい。

### ISSUE THREAD

**Issue by m-takata** [nimbus-org/nimbus#104]
DefaultPropertySchemaの制約は、Jexlで書くことができるが、表現能力が限られている。サービスで定義したInterpreterで、制約式を評価することができるようにして欲しい。

**Comment by m-takata** [comment]
マージしたので、確認お願い。 @y-nakashima0324

**Comment by y-nakashima0324** [comment]
期待通り動作を確認しました。
クローズします。
