### ISSUE TITLE
DefaultPersistantManagerでNumber型カラムのNull値扱いについて

### ISSUE THREAD

**Issue by h-masaoka** [nimbus-org/nimbus#129]
下記の条件で、DefaultPersistentManagerServiceを使ってDBカラムをRecordListのカラムに変換する際に、nullの値が0に変換される事象が発生します。

・DBカラムがNUMBER型、値はnull
・RecordListのカラムはint型

DBカラムがNUMBER型でnullの値の場合に、nullが返却されなくなりました。
以前のNimbusバージョン(1.2.0)ではnullを返却できました。
アプリ側では、nullと0を分けて扱っております。

**Comment by m-takata** [comment]
修正しました。
