### ISSUE TITLE
ThreadLocalのメモリーリーク

### ISSUE THREAD

**Issue by y-nakashima0324** [nimbus-org/nimbus#134]
ThreadLocalを使用するサービスの停止時に、memory leak checkに引っかかり"重大"ログが吐かれる。

12-Jul-2018 16:36:57.743 重大 [main] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [dl] created a ThreadLocal with key of type [jp.ossc.nimbus.service.aop.interceptor.MethodJournalInterceptorService$1] (value [jp.ossc.nimbus.service.aop.interceptor.MethodJournalInterceptorService$1@5a95aaae]) and a value of type [jp.ossc.nimbus.service.aop.interceptor.MethodJournalInterceptorService.CallStack] (value [jp.ossc.nimbus.service.aop.interceptor.MethodJournalInterceptorService$CallStack@519e67e]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

**Comment by m-takata** [comment]
ThreadLocalを、スレッド単位のインスタンス変数的な役割で利用していたり、staticに利用していたりするので、ThreadLocalを掃除することは、できません。

**Comment by m-takata** [comment]
Tomcatが、メモリリークかどうかはっきりと判断できないのに、ERRORレベルでログを吐いているのが、どうかと思います。
そのログを無視する方向でお願いします。
