### ISSUE TITLE
MessageForwardingServiceのフェイルオーバー時のメッセージ補完について

### ISSUE THREAD

**Issue by h-masaoka** [nimbus-org/nimbus#139]
冗長化サーバ構成をとっているMessageForwardingServiceにおいて、主系サーバのプロセスを落として待機系にフェイルオーバーさせたところ、待機系に切り替わるまで間のメッセージがフォワード先のフロント系サーバ側で補完されていないという事象が起きています。
※Feedのフェイルオーバー時は問題なく補完できています。
  
フェイルオーバー時のstartReceive()処理で
```java
time = System.currentTimeMillis() - failoverBufferTime;
connection.startReceive(time);
```
されているようにfailoverBufferTimeの時間だけ遡って受信を開始していると思っています。
  
FeedおよびForward側で
SendMessageCacheTime＝90秒、failoverBufferTime＝60秒
設定はしているのですが、他に考慮すべき設定等はありますでしょうか？
  
  
以前「server側とclient側でKeepAliveのheartbeat_intervalが同じだと良くない」
という話を軽く伺いましたが、その辺りと関係はあったりしますでしょうか？

**Comment by m-takata** [comment]
ClusterServiceのハートビートは、クライアントの方がサーバより長くすべき。
そうしておかないと、サーバがフェイルオーバした時に、サーバの待機系が稼働系が死んだのを検知するよりも早く、クライアントが稼働系が死んだのを検知してしまい、クラスタから切り離されてしまう。
クライアントの方のハートビートを長くしておくことで、クライアントよりも早くサーバの待機系が稼働系が死んだのを検知し、メンバ変更通知をクライアントに送るため、クラスタから切り離されなくなる。

**Comment by m-takata** [comment]
調査した結果、フェイルオーバした際に、補完がうまくいかない理由がいくつかありました。

- MessageForwardServiceのStartReceiveOnStart属性をtrueに設定していたため、MessageForwardServiceが起動した直後に受信開始状態になっている。そのため、フェイルオーバした際に、クライアントが時間を遡って受信開始要求を行っても、既に受信開始しており、送信バッファも空のため、補完が行われない。
→フェイルオーバさせたい場合は、StartReceiveOnStart属性は、falseを設定すること。
- ClusterClientConnectionFactoryServiceで、フェイルオーバの際に、最終受信時刻から遡って受信する機能がある。そのために、最後に受信したメッセージを保持しておき、フェイルオーバ時にそのメッセージの受信時刻を使用する。しかし、受信したメッセージが再利用されている可能性があり、その場合、メッセージの受信時刻は定かではない。
→メッセージを保持せずに、メッセージの受信時刻を保持するように改修した。
- jp.ossc.nimbus.service.publish.udp.ConnectionFactoryServiceで、マルチキャストを利用している場合、実装上、サーバ側は基本的にすべてのクライアントに同じメッセージを配信して、受信したクライアント側でサブジェクトとキーによるフィルタリングを行う。つまり、サーバ側は、クライアント毎に送信管理を行っていない。この接続を利用して、ClusterClientConnectionFactoryServiceを使用している場合、上述したフェイルオーバに使用する最終受信時刻は、フィルタされた後のメッセージの受信時刻となる。そうすると、フェイルオーバ時に最初に受信開始要求を行ってきたクライアントの最終受信時刻に依存するため、クライアント毎にサブジェクトやキーが異なる場合、他のクライアントにとっては、最終受信時刻が大きく異なる場合があり、ロストの原因となる。
→マルチキャストの場合、最終受信時刻をフィルタする前のメッセージの受信時刻を使用するように改修した。

**Comment by h-masaoka** [comment]
非常によく分かりました！！ありがとうございます
