### ISSUE TITLE
取引のシミュレーションを行う機能をフレームワーク化したい

### ISSUE THREAD

**Issue by m-takata** [nimbus-org/nimbus#156]
株式などの金融商品を取引する際に、売買タイミングを知らせる売買サインを使用した自動取引を行う要求がある。
その場合に、売買サインには、多様な実装が考えられる。
それらの売買サインのパフォーマンスを評価するために、過去の価格推移に対して、取引をシミュレートする必要がある。
売買サインを抽象化し、取引シミュレーションを行うフレームワークが欲しい。

**Comment by m-takata** [comment]
検討したいこと。
・取引のシミュレート
・取引のパフォーマンス評価
・遺伝的アルゴリズムを用いた、取引シミュレートの最適化
・余力を考慮した取引のシミュレート
・複数の取引候補の優先順位付け
・取引サインの実装

**Comment by y-nakashima0324** [comment]
引き継ぎました。
#479から最新マージ。
m-aono分マージ。

**Comment by m-takata** [comment]
マージしたので、クローズします。
