### ISSUE TITLE
SharedContextサービス起動時にClusterMemberの数とServerConnectionが認識しているClientの数が合わずに起動しない

### ISSUE THREAD

**Issue by recoba0507** [nimbus-org/nimbus#159]

**Comment by recoba0507** [comment]
SharedContextサービス起動時にClusterサービスが認識しているメンバーが全てConnectionが接続できているか確認する処理で、Clusterメンバーの数とServerConnectionが認識しているClientの数が合わずにタイムアウトが発生して起動できない。

**Comment by m-takata** [comment]
#152の改修影響のようです。
対応します。

**Comment by m-takata** [comment]
#152の対応を、明示的に設定した時だけ、動作が変わるように変更しました。

**Comment by m-takata** [comment]
確認して頂いたので、クローズします。
