### ISSUE TITLE
Beanflowにて@inputDef(input name).属性名@でアクセスできない

### ISSUE THREAD

**Issue by y-nakashima0324** [nimbus-org/nimbus#171]
Beanflowにて@inputDef(input name).属性名@でアクセスできない。
＠input name.属性名＠ではできる。

**Comment by m-takata** [comment]
変数名（input-defのname属性の値）で、直接アクセス可能にしたことによる、デグレードです。
両方できるように、直せそうか見てみます。

**Comment by m-takata** [comment]
改修しました。
