### ISSUE TITLE
DataSetCodeGeneratorでエラーが発生した際の特定が難しい

### ISSUE THREAD

**Issue by ishidamu** [nimbus-org/nimbus#173]
DataSetCodeGeneratorでのエラー時のメッセージに何が悪いかの情報がほしいです。

**Comment by m-takata** [comment]
DataSetCodeGeneratorを使って、スキーマ定義をした時に、プロパティの型を定義しないと、NullPointerExceptionが発生した。

**Comment by m-takata** [comment]
DefaultPropertySchema.getType()が、プロパティの型を定義していない場合は、nullを返す仕様となっていたのを、Object.classを返すように修正した。

これによって、上記のNullPointerExceptionは発生しないようになった。
