### ISSUE TITLE
サーバコネクションのisStartReceiveの不正について

### ISSUE THREAD

**Issue by dengguoqingZone** [nimbus-org/nimbus#177]
株アプリでRRと価格アラートの間に通信の問題が発生した。現象は通信グループの仲間として認識できているにも関わらず、SharedContextのサーバ側のisStartReceiveはfalseになっていた。
再現方法は今段階は不明。

**Comment by m-takata** [comment]
ClientConnectionのclose()を呼んでも、isStartReceive()がfalseにならないため、同じインスタンスでconnect()してstartReceive()すると、ServerConnectionにstartReceive()が伝搬されないという動作をする可能性があります。
ただ、この問題を踏んだことで、現象が発生しているのかは、推論でしかないので、現象の再現性を明確にして下さい。

上記の問題の改修は、ブランチで行います。

**Comment by m-takata** [comment]
ブランチで修正して、masterにマージしました。
動作確認をお願いしたいところですが、再現手順も明確でないということなので、一旦クローズします。
再現手順が明確になり、最新のモジュールでも問題があるようなら、また起票してください。
