### ISSUE TITLE
AuthenticateInterceptorServiceでThreadContextに認証情報が設定されないことがある

### ISSUE THREAD

**Issue by ishidamu** [nimbus-org/nimbus#18]
Sessionが破棄されるタイミングと処理が動くタイミングによって、発生する可能性がある。

**Comment by ishidamu** [comment]
マージされたので、クローズする。ワン。

**Comment by m-takata** [comment]
リクエストを受け付けて、処理している間にセッションがタイムアウトするなんて、アプリケーションサーバの同期処理の問題だとは、思うけどね。
仕方ないね。
