### ISSUE TITLE
複数のBeanFlowの非同期呼び出しを待つ場合に、replay nameの指定のみでは待合せできない。

### ISSUE THREAD

**Issue by y-nakashima0324** [nimbus-org/nimbus#186]
以下だと、ReplyedCallのresultが上書かれてしまい、待合せができなくなる。
```xml
        <for var="Record1">
            <target><input name="List"/></target>
            <callflow name="sub" stepname="ReplyedCall" asynch="true" reply="true"/>
            <step name="TargetCount">
                <result><expression>TargetCount+1</expression></result>
            </step>
        </for>
        
        <!-- 待合せ -->
        <for index="i" begin="0" end="@TargetCount@">
            <reply name="ReplyedCall"/>
        </for>
```
この形式でも動くようにする or 上書きエラー などの修正を求む。

**Comment by m-takata** [comment]
reply要素のname属性は、本来、reply要素自体のstep名です。
待ち合わせするcallflow要素のstep名は、reply要素のstepname属性で指定します。

上記のように書いてしまうと、
callflowした要素の結果（非同期呼び出しの待ち合わせ情報）を、replyで取り出した非同期呼び出しの戻り値で、上書きしてしまうので、replyしているforループの2回目以降で、非同期呼び出しの結果が取り出せなくなってしまいます。

従って、上記の場合だと
```xml
        <for var="Record1">
            <target><input name="List"/></target>
            <callflow name="sub" stepname="ReplyedCall" asynch="true" reply="true"/>
            <step name="TargetCount">
                <result><expression>TargetCount+1</expression></result>
            </step>
        </for>
        
        <!-- 待合せ -->
        <for index="i" begin="0" end="@TargetCount@">
            <reply name="Replyed" stepname="ReplyedCall"/>
        </for>

```
と記述するのが、正解です。
reply要素のstepname属性は、省略可能で、省略した場合、name属性の値が採用されます。

これは、非同期呼び出しを１回しかしない場合、簡略化するための機能です。
例えば、
```xml
        <callflow name="sub" stepname="ReplyedCall" asynch="true" reply="true"/>
        <reply name="ReplyedCall"/>

```
といった場合です。
この場合だと、callflowした要素の結果（非同期呼び出しの待ち合わせ情報）を、replyで取り出した非同期呼び出しの戻り値で、上書きしても、そもそも問題がないため、わざわざ、別のstep名称を持たせる必要がなく、reply要素のstepname属性を省略しても良いということです。

**Comment by m-takata** [comment]
ただ、ご指摘の通り、間違いが起こりやすい仕様だと言えます。
間違いが起きた場合に、明確なエラーにもならないため、分かりにくい問題となってしまいます。
現行の動作保証の必要があるため、仕様を変更することはできませんが、誤った使用方法の場合に、例外が投げれないか、検討してみます。

**Comment by m-takata** [comment]
以下のような修正を行いました。

1. reply要素のname属性を必須からオプションに変更。
2. reply要素のname属性のみを指定している場合、またはstepname属性とname属性に同じ値が指定されている場合は、実行時に、複数回のreplyが可能な場合は、例外を発生させるようにした。
3. reply要素で指定されたstepname（stepname属性を省略した場合のnameも含む）で指定したものが、callflow要素ではない場合は、例外をthrowするようにした。

今回の場合だと、2の修正によって、例外が発生するようになります。
