### ISSUE TITLE
DefaultPropertySchemaでConverterありのParse時に自動で型変換してほしい

### ISSUE THREAD

**Issue by ishidamu** [nimbus-org/nimbus#235]

**Comment by m-takata** [comment]
今の実装は、Converterをスキーマに指定している場合は、Converterに変換の責務が全て課されている。
Converterをスキーマに指定していない場合は、スキーマの型と設定値の型が合わない場合は、設定値の型がString及びString[]の場合のみ、PropertyEditorによる型変換を自動で行う。

このConverterをスキーマに指定していない場合の自動型変換の機能を、Converterをスキーマに指定している場合でも、Converterに変換結果の型がスキーマの型と合わない場合は、有効になるようにします。

**Comment by m-takata** [comment]
改修して、マージしたので、close
