### ISSUE TITLE
FLV形式のバイト配列とRecordの相互変換機能がほしい

### ISSUE THREAD

**Issue by ishidamu** [nimbus-org/nimbus#246]
・FLVStreamRecordReader
・FLVStreamRecordWriter
　StreamとRecordを相互変換する
・StringByteArrayConverter
　文字列とByte配列を変換するコンバータ
・PaddingByteConverter
　Byteでパディングするコンバータ

**Comment by m-takata** [comment]
・FLVInputStream
・FLVOutputStream
もだよね。

**Comment by m-takata** [comment]
今回の要望の元は、行セパレータを含まないFLV形式の文字列（2バイト文字を含む）を、FLVRecordReaderで処理すると、うまく読み込めないところが、発端となっている。

行セパレータを含まないFLV形式の文字列をFLVRecordReaderで処理できるようにする対応を、
 #237
で行ったが、その対応が不十分であったことが分かった。
FLVRecordReaderは、もともと、バイト長で処理していたが、行セパレータを含まないFLV形式の文字列を処理する場合のみ、文字列長で処理するようになっていた。
それを、バイト長で処理するように改修することで、問題が解決するのではないか？

**Comment by m-takata** [comment]
追加で、PaddingStringConverterに、以下の不具合があったので、直しました。
・isCountTwiceByZenkaku=trueの場合に、全角文字が混ざった文字をパースすると、StringIndexOutOfBoundsExceptionが発生する不具合を修正した。

**Comment by m-takata** [comment]
結局、要求の機能も追加して、マージしました。
