### ISSUE TITLE
Publisher電文で補間エラーが出続け、電文が滞留する現象が発生

### ISSUE THREAD

**Issue by h-takehashi** [nimbus-org/nimbus#334]
NimbusPublisherのServerConnection側において、
```
2019/05/31 05:20:27,UNKNOWN,SYSTEM_ERROR,[PCFT_00007]メッセージを補間できませんでした。client=jp.ossc.nimbus.service.publish.udp.ServerConnectionImpl$ClientImpl@102120c2{factory=ForwardMulticastServer.Connection#IndexServerConnectionFactory, client=/***.**.***.**:*****, subject={703=[null], 704=[null], 701=[null], 702=[null]}, isEnabled=true}, id=jp.ossc.nimbus.service.publish.udp.MessageId@1{sequence=1}-jp.ossc.nimbus.service.publish.udp.MessageIdjp.ossc.nimbus.service.publish.udp.MessageId@1{sequence=1}{sequence=1}, count=1, mostOldId=1, mostOldTime=Fri May 31 05:20:27 JST 2019
```
というエラーメッセージが500ms毎に出続けるようになり、以後、ClientConnection側で電文は受信しているが滞留してしまう状況となりました。
(ClientConnection側においてはエラーは一切出力されていません)
/jp/ossc/nimbus/service/publish/udp/ClientConnectionImpl.java
のconsumeメソッドで、UDP電文を管理するTreeMap(Keyは電文のSequenceNo)に入り得ないKey=0が登録され、このKeyの電文が補間できず、以後の電文は受信しているが送出できず滞留する現象が起きていたようです。
TreeMapにKey=0が登録される原因を調査いただけないでしょうか。

**Comment by m-takata** [comment]
UDPのConnectionFactoryは、Messageを送信する際に、一定サイズのWindowに分割して送信します。
分割されたWindowを受信し、元のMessageに復元してから、受信を行いますが、UDPプロトコルでは順序性保証が行われないため、Windowの到着順が、逆転することがあります。
また、UDPプロトコルでは到達保証も行われないため、Windowが届かない場合もあります。
そのような仕組み上、受信したWindowが、分割されたものの一部である場合、一旦、内部のMapに、格納され、残りのWindowの受信を待つ仕組みとなってます。その際、そのMapのキーが、Messageの順序性を示すメッセージIDとなっているのですが、本来、1番となるべきメッセージIDが0番となってしまい、待機用のMapに格納されてしまいました。
しばらく待機した後、残りのWindowが到着しない場合は、送信元へ補完要求を行いますが、Messageは1番からしか存在しないため、補完できず無限に待ち続ける状態に嵌ってしまいました。

このMapのキーとして格納されるメッセージIDは、到着したWindowから取得され、本来は、Windowの持つメッセージIDと同じ値になります。障害発生時の調査から、Mapの値に格納されていたWindowのメッセージIDは1だったことが確認できています。

Windowの持つメッセージIDが、一時的に0になる可能性は、Windowの再利用によるものです。
再利用されたWindowは、本来、１つのスレッドから参照されますが、再利用処理の不具合により、複数のスレッドから参照される可能性があることがわかってます。
本不具合は、issueの#296で改修しています。

上記の不具合を、踏んだのかは、ソースレベルでの調査による可能性論であり、確かではありません。
再現性の確認とともに、最新のビルドでのご確認をお願いします。

**Comment by m-takata** [comment]
進展がないため、一旦closeします。
