### ISSUE TITLE
SharedContextのupdateとonUpdateが並列で処理された場合にindexManagerのreplace処理で例外が発生する場合がある

### ISSUE THREAD

**Issue by recoba0507** [nimbus-org/nimbus#366]
SharedContextのupdateとonUpdateが同時並行で実行された場合に発生する。
onUpdateで更新する場合にローカルデータを一度削除するが、その影響でupdateの中で呼ばれるindexManager.replaceメソッドに渡すoldValueがタイミングによってnullとなりNullPointerExceptionが発生してしまう。

**Comment by m-takata** [comment]
修正しました。

但し、上記の発生原因は、ロックせずに、更新を並列で行っていることであり、その場合に、NullPointerExceptionが発生しないようには改修しましたが、正しく更新されることを保証できるものではありません。
