### ISSUE TITLE
SharedCotextServiceのonUpdate処理でindexの更新処理が実行されていない

### ISSUE THREAD

**Issue by recoba0507** [nimbus-org/nimbus#367]
onUpdateの中でローカルに保持しているindex情報に対して受信した更新情報でindex情報を最新かしていない。したがって、更新する可能性のあるプロパティに対してindexを設定している場合は、更新した内容がindexに反映されない。

**Comment by m-takata** [comment]
修正しました。

但し、インデックスを張っているプロパティに対して、差分更新を行った場合、クライアントモードではインデックスが更新されない仕様上の制約があります。
その旨、JavaDocに追記しました。
