### ISSUE TITLE
テストフレームワークの品質向上

### ISSUE THREAD

**Issue by ishidamu** [nimbus-org/nimbus#37]
テストフレームワークを使用しているとたまに正常に動作しないことがある。
品質向上を行う必要がある。

**Comment by m-takata** [comment]
ConsoleTestEstimateReporterServiceなどの見積もりを出力するTestReporterで出力されたシナリオの見積もりが０になってしまう。

**Comment by m-takata** [comment]
ConsoleTestEstimateReporterServiceなどの見積もりを出力するTestReporterで、テストケースの見積もりを出力する実装がない。

**Comment by m-takata** [comment]
TestSwingRunnerの実行状態に表示されるステータス文字列の意味がわからない。

**Comment by ishidamu** [comment]
> ConsoleTestEstimateReporterServiceなどの見積もりを出力するTestReporterで、テストケースの見積もりを出力する実装がない。

テストケースの見積もりは出さない仕様でした。
テストケースの見積もり工数が存在する場合は、テストシナリオ内の工数に加算して出力していました。

**Comment by ishidamu** [comment]
> ConsoleTestEstimateReporterServiceなどの見積もりを出力するTestReporterで出力されたシナリオの見積もりが０になってしまう。

バグってたので修正しました。プルプル出したのでマージしてください。ワン。

**Comment by m-takata** [comment]
TestSwingRunnerが、サービス定義の読み込みに失敗しても、起動してしまう。

**Comment by m-takata** [comment]
TestSwingRunnerで、テストケースがNGになると、再実行できなくなる。
一応、シナリオから再実行しなおすと、テストケースも再実行可能にはなる。

**Comment by ishidamu** [comment]
> TestSwingRunnerの実行状態に表示されるステータス文字列の意味がわからない。
対応しました～

> シナリオグループのXMLで、action要素にretryInterval属性及びretryCount属性が指定できない。
対応しました～

残は以下。

> TestSwingRunnerで、テストケースがNGになると、再実行できなくなる。

**Comment by ishidamu** [comment]
> TestSwingRunnerで、テストケースがNGになると、再実行できなくなる。

とりあえず、修正してみた。大丈夫かなぁ。。。

**Comment by m-takata** [comment]
テストリソースのresourceタグ内に、xmlエスケープ対象文字を書きたい時に、エスケープするのが面倒なので、BeanFlowと同じようにXMLコメントアウトをresourceタグに書けるようにして欲しい。

**Comment by ishidamu** [comment]
このIssueは一旦クローズする。
不具合等があれば、別のIssueで対応する。
