### ISSUE TITLE
BeanFlowで、RecordListをforなどの繰り返し処理すると、ループが遅い問題

### ISSUE THREAD

**Issue by ishidamu** [nimbus-org/nimbus#4]
RandomAccessをimplementsする

**Comment by m-takata** [comment]
タイトルおかしくない？

**Comment by m-takata** [comment]
BeanFlowで、RecordListをforなどの繰り返し処理すると、ループが遅い問題の対応として、RandomAccessインタフェースを実装するってことだよね。

**Comment by m-takata** [comment]
pull requestをマージしました。
