### ISSUE TITLE
Nimbusコンソール上でコネクションが表示されない

### ISSUE THREAD

**Issue by h-masaoka** [nimbus-org/nimbus#43]
同じConnectionFactoryを使って複数のConnectionを作ったときに、1番最初か1番最後かの1つのConnectionしかNimbus-Consoleに表示されない。

**Comment by m-takata** [comment]
生成されたClientConnectionを、自動的にNimbusのサービスとして登録する。
その際に、サービス名の一意性担保のために、受信ポート利用するが、マルチキャストの場合、受信ポートでは一意性を担保できない。
そのため、同じClientConnectionFactoryから複数のClientConnectionを生成した場合、最初の１つしかサービスとして登録されない不具合がある。

**Comment by m-takata** [comment]
改修して、masterにマージしました。
確認してください。 @h-masaoka
