### ISSUE TITLE
テストフレームワークでTCPテキストベースのスタブを作成してください。

### ISSUE THREAD

**Issue by ishidamu** [nimbus-org/nimbus#51]

**Comment by y-nakashima0324** [comment]
さっくり作ります

**Comment by y-nakashima0324** [comment]
高田さんレビュー
・setter, getterの確認
・DefaultRequestMsgはResponseでは？
・oswにwriteする文字列は、一旦文字列を作らずに直接oswに書き込む
・Patternオブジェクトは毎回作らずに、スタートでつくっておく
・readInputStream
　・今の実装では改行コードが消える
　　・BufferedReaderでなく、InputSreamReaderで読んでいく
　・nullチェック不要

**Comment by m-takata** [comment]
マージしたので、クローズ
