### ISSUE TITLE
PersistentManagerのloadQueryにて、埋め込めクエリに埋め込み先がない場合inputを渡すとエラーが発生する

### ISSUE THREAD

**Issue by t2-tashiro** [nimbus-org/nimbus#556]
埋め込みクエリに？（埋め込み先）がなくてもINPUTにNULL以外を渡したい。

動的な埋め込みクエリを使う場合、条件によっては埋め込みクエリに？（埋め込み先）がなくなる。
条件によってINPUTに {NULL or NULL以外}を渡すという分岐を省略したい。

**Comment by m-takata** [comment]
埋め込みパラメータがないクエリなのに、入力オブジェクトを指定するのは、本来的には、渡すべきではない。
ただ、クエリを動的に作る場合など、結果的に埋め込みパラメータが存在しなくなる場合に、入力オブジェクトを渡してはならないのは、冗長なコードを生んでしまうことになる。

JDBCドライバが実装されていれば、ParameterMetaDataによって、クエリにパラメータが存在するかどうか判定可能なので、パラメータが存在しない場合は、入力オブジェクトを渡されても無視するようにします。

**Comment by m-takata** [comment]
対応しました。
