### ISSUE TITLE
SharedQueueのget処理で無限ループが発生することがある

### ISSUE THREAD

**Issue by recoba0507** [nimbus-org/nimbus#557]
SharedQueueのget処理で、ローカルでのQueueのサイズが1以上でlockFirtst処理でkeyが取得できない場合無限ループとなってしまう。
リモートとローカルでQueueのサイズに不整合が発生した場合に起きる。

**Comment by m-takata** [comment]
上記の現象には、２つの問題点があると思います。
（１）Mainのノードと、そうでないノードで、Queueのサイズが異なる状態になった要因があること。
（２）（１）の状態になった場合で、Mainは０件なのに、Mainでないノードが0件でない場合、Mainではロックできるデータがないのに、Mainでないノードは、データを持っているつもりで、ロック要求を行い、その結果ロックできるものがないと応答された場合に、再度ロック要求をしてしまい、無限ループに陥る。

現段階では、（１）の原因が分かりません。
ただ、（２）の問題は、ノード間のデータの不整合を検知したと捉えて、Mainノードとの同期をとるという改修が可能だと思います。

**Comment by m-takata** [comment]
（２）の改修も、データの不整合の検知が、困難なことが分かりました。
現状では、（２）の改修方法も困難なので、（１）の要因を明らかにするしかありません。

最新のNimbusでの挙動確認が取れていないという事なので、一旦最新化して、ご確認ください。

**Comment by m-takata** [comment]
無限ループになる要因は、lockFirst()はMainで処理し、size()はサーバモードで処理するため、Mainのノードと、Mainではないサーバモードのノードで、データ不整合が起きると、整合性が取れなくなり、無限ループロジックにはまり込むことです。

そこで、lockFirst()をMainではなく、サーバモードのノードで行うように改修してみました。
簡単な動作確認は、できてますので、ブランチのモジュールで、動作確認をお願いします。

**Comment by m-takata** [comment]
masterにマージしたので、一旦クローズします。
