### ISSUE TITLE
schemaが無いDataSetをジャーナルで出力しようとするとNullPointerExceptionが発生する。

### ISSUE THREAD

**Issue by shoeimotomura** [nimbus-org/nimbus#564]
以下、ログです。

発生例外:Exception occuers :jp.ossc.nimbus.service.beancontrol.interfaces.BeanControlUncheckedException: Target Error occured. flowName=/ProbeHealthCheck
	jp.ossc.nimbus.service.beancontrol.BeanFlowInvokerAccessImpl2.throwException(BeanFlowInvokerAccessImpl2.java:1112)
	jp.ossc.nimbus.service.beancontrol.BeanFlowInvokerAccessImpl2.invokeFlowInternal(BeanFlowInvokerAccessImpl2.java:1053)
	jp.ossc.nimbus.service.beancontrol.BeanFlowInvokerAccessImpl2.invokeFlowWithTransaction(BeanFlowInvokerAccessImpl2.java:915)
	jp.ossc.nimbus.service.beancontrol.BeanFlowInvokerAccessImpl2.invokeFlow(BeanFlowInvokerAccessImpl2.java:709)
	sun.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	jp.ossc.nimbus.service.aop.invoker.MethodReflectionCallInvokerService.invoke(MethodReflectionCallInvokerService.java:102)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:231)
	jp.ossc.nimbus.service.aop.interceptor.ExceptionHandlingInterceptorService.invoke(ExceptionHandlingInterceptorService.java:208)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.service.aop.interceptor.BeanFlowMetricsInterceptorService.invoke(BeanFlowMetricsInterceptorService.java:549)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.service.aop.interceptor.MethodJournalInterceptorService.invoke(MethodJournalInterceptorService.java:449)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.service.beancontrol.DefaultBeanFlowInvokerFactoryService$WrappedBeanFlowInvoker.invokeFlow(DefaultBeanFlowInvokerFactoryService.java:1474)
	jp.ossc.nimbus.service.beancontrol.DefaultBeanFlowInvokerFactoryService$WrappedBeanFlowInvoker.invokeFlow(DefaultBeanFlowInvokerFactoryService.java:1461)
	jp.ossc.nimbus.servlet.BeanFlowServlet.processAction(BeanFlowServlet.java:623)
	jp.ossc.nimbus.servlet.BeanFlowServlet.doService(BeanFlowServlet.java:526)
	jp.ossc.nimbus.servlet.BeanFlowServlet.doPost(BeanFlowServlet.java:429)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	jp.ossc.nimbus.servlet.InterceptorChainCallFilter.invoke(InterceptorChainCallFilter.java:275)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:231)
	jp.ossc.nimbus.service.aop.interceptor.servlet.ExceptionHandlingInterceptorService.invokeFilter(ExceptionHandlingInterceptorService.java:209)
	jp.ossc.nimbus.service.aop.interceptor.servlet.ServletFilterInterceptorService.invoke(ServletFilterInterceptorService.java:288)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.service.aop.interceptor.servlet.StreamExchangeInterceptorService.invokeFilter(StreamExchangeInterceptorService.java:916)
	jp.ossc.nimbus.service.aop.interceptor.servlet.ServletFilterInterceptorService.invoke(ServletFilterInterceptorService.java:288)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.service.aop.interceptor.servlet.HttpServletRequestMetricsInterceptorService.invokeFilter(HttpServletRequestMetricsInterceptorService.java:551)
	jp.ossc.nimbus.service.aop.interceptor.servlet.ServletFilterInterceptorService.invoke(ServletFilterInterceptorService.java:288)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.service.aop.interceptor.servlet.BeanFlowSelectCheckInterceptorService.invokeFilter(BeanFlowSelectCheckInterceptorService.java:128)
	jp.ossc.nimbus.service.aop.interceptor.servlet.ServletFilterInterceptorService.invoke(ServletFilterInterceptorService.java:288)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.service.aop.interceptor.servlet.HttpServletRequestCheckInterceptorService.invokeFilter(HttpServletRequestCheckInterceptorService.java:755)
	jp.ossc.nimbus.service.aop.interceptor.servlet.ServletFilterInterceptorService.invoke(ServletFilterInterceptorService.java:288)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.service.aop.interceptor.servlet.ExceptionHandlingInterceptorService.invokeFilter(ExceptionHandlingInterceptorService.java:209)
	jp.ossc.nimbus.service.aop.interceptor.servlet.ServletFilterInterceptorService.invoke(ServletFilterInterceptorService.java:288)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.service.aop.interceptor.servlet.HttpServletResponseDeflateInterceptorService.invokeFilter(HttpServletResponseDeflateInterceptorService.java:219)
	jp.ossc.nimbus.service.aop.interceptor.servlet.ServletFilterInterceptorService.invoke(ServletFilterInterceptorService.java:288)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.service.aop.interceptor.servlet.ServletResponseSetInterceptorService.invokeFilter(ServletResponseSetInterceptorService.java:112)
	jp.ossc.nimbus.service.aop.interceptor.servlet.HttpServletResponseSetInterceptorService.invokeFilter(HttpServletResponseSetInterceptorService.java:204)
	jp.ossc.nimbus.service.aop.interceptor.servlet.ServletFilterInterceptorService.invoke(ServletFilterInterceptorService.java:288)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.service.aop.interceptor.servlet.AccessJournalInterceptorService.invokeFilter(AccessJournalInterceptorService.java:570)
	jp.ossc.nimbus.service.aop.interceptor.servlet.ServletFilterInterceptorService.invoke(ServletFilterInterceptorService.java:288)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.service.aop.interceptor.servlet.ServletRequestInitializeInterceptorService.invokeFilter(ServletRequestInitializeInterceptorService.java:197)
	jp.ossc.nimbus.service.aop.interceptor.servlet.ServletFilterInterceptorService.invoke(ServletFilterInterceptorService.java:288)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.service.aop.interceptor.servlet.ThreadContextInitializeInterceptorService.invokeFilter(ThreadContextInitializeInterceptorService.java:395)
	jp.ossc.nimbus.service.aop.interceptor.servlet.ServletFilterInterceptorService.invoke(ServletFilterInterceptorService.java:288)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.service.aop.interceptor.servlet.SetCharacterEncodingInterceptorService.invokeFilter(SetCharacterEncodingInterceptorService.java:128)
	jp.ossc.nimbus.service.aop.interceptor.servlet.ServletFilterInterceptorService.invoke(ServletFilterInterceptorService.java:288)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.service.aop.interceptor.RequestProcessCheckInterceptorService.invoke(RequestProcessCheckInterceptorService.java:304)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.servlet.InterceptorChainCallFilter.doFilter(InterceptorChainCallFilter.java:245)
	org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	org.apache.catalina.filters.CorsFilter.handleSimpleCORS(CorsFilter.java:259)
	org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:163)
	org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
	org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:748)
Caused by:java.lang.NullPointerException
	jp.ossc.nimbus.service.journal.editor.RecordJournalEditorService.makePropertiesFormat(RecordJournalEditorService.java:194)
	jp.ossc.nimbus.service.journal.editor.RecordJournalEditorService.processBlock(RecordJournalEditorService.java:169)
	jp.ossc.nimbus.service.journal.editor.BlockJournalEditorServiceBase.toString(BlockJournalEditorServiceBase.java:110)
	jp.ossc.nimbus.service.journal.editor.ImmutableJournalEditorServiceBase.toString(ImmutableJournalEditorServiceBase.java:146)
	jp.ossc.nimbus.service.journal.editor.ImmutableJournalEditorServiceBase.toObject(ImmutableJournalEditorServiceBase.java:137)
	jp.ossc.nimbus.service.journal.JournalRecordImpl.setInfoObj(JournalRecordImpl.java:119)
	jp.ossc.nimbus.service.journal.RequestJournalImpl.setInfoObj(RequestJournalImpl.java:196)
	jp.ossc.nimbus.service.journal.ThreadManagedJournalService.addInfo(ThreadManagedJournalService.java:470)
	jp.ossc.nimbus.service.beancontrol.BeanFlowInvokerAccessImpl2$ObjectMetaData.getValue(BeanFlowInvokerAccessImpl2.java:2017)
	jp.ossc.nimbus.service.beancontrol.BeanFlowInvokerAccessImpl2$StepMetaData.invokeStep(BeanFlowInvokerAccessImpl2.java:1682)
	jp.ossc.nimbus.service.beancontrol.BeanFlowInvokerAccessImpl2.invokeFlowInternal(BeanFlowInvokerAccessImpl2.java:1012)
	jp.ossc.nimbus.service.beancontrol.BeanFlowInvokerAccessImpl2.invokeFlowWithTransaction(BeanFlowInvokerAccessImpl2.java:915)
	jp.ossc.nimbus.service.beancontrol.BeanFlowInvokerAccessImpl2.invokeFlow(BeanFlowInvokerAccessImpl2.java:709)
	sun.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	jp.ossc.nimbus.service.aop.invoker.MethodReflectionCallInvokerService.invoke(MethodReflectionCallInvokerService.java:102)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:231)
	jp.ossc.nimbus.service.aop.interceptor.ExceptionHandlingInterceptorService.invoke(ExceptionHandlingInterceptorService.java:208)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.service.aop.interceptor.BeanFlowMetricsInterceptorService.invoke(BeanFlowMetricsInterceptorService.java:549)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.service.aop.interceptor.MethodJournalInterceptorService.invoke(MethodJournalInterceptorService.java:465)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.service.beancontrol.DefaultBeanFlowInvokerFactoryService$WrappedBeanFlowInvoker.invokeFlow(DefaultBeanFlowInvokerFactoryService.java:1474)
	jp.ossc.nimbus.service.beancontrol.BeanFlowInvokerAccessImpl2$CallFlowMetaData.invokeStep(BeanFlowInvokerAccessImpl2.java:4127)
	jp.ossc.nimbus.service.beancontrol.BeanFlowInvokerAccessImpl2.invokeFlowInternal(BeanFlowInvokerAccessImpl2.java:1012)
	jp.ossc.nimbus.service.beancontrol.BeanFlowInvokerAccessImpl2.invokeFlowWithTransaction(BeanFlowInvokerAccessImpl2.java:915)
	jp.ossc.nimbus.service.beancontrol.BeanFlowInvokerAccessImpl2.invokeFlow(BeanFlowInvokerAccessImpl2.java:709)
	sun.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	jp.ossc.nimbus.service.aop.invoker.MethodReflectionCallInvokerService.invoke(MethodReflectionCallInvokerService.java:102)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:231)
	jp.ossc.nimbus.service.aop.interceptor.ExceptionHandlingInterceptorService.invoke(ExceptionHandlingInterceptorService.java:208)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.service.aop.interceptor.BeanFlowMetricsInterceptorService.invoke(BeanFlowMetricsInterceptorService.java:549)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.service.aop.interceptor.MethodJournalInterceptorService.invoke(MethodJournalInterceptorService.java:465)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.service.beancontrol.DefaultBeanFlowInvokerFactoryService$WrappedBeanFlowInvoker.invokeFlow(DefaultBeanFlowInvokerFactoryService.java:1474)
	jp.ossc.nimbus.service.beancontrol.BeanFlowInvokerAccessImpl2$CallFlowMetaData.invokeStep(BeanFlowInvokerAccessImpl2.java:4127)
	jp.ossc.nimbus.service.beancontrol.BeanFlowInvokerAccessImpl2.invokeFlowInternal(BeanFlowInvokerAccessImpl2.java:1012)
	jp.ossc.nimbus.service.beancontrol.BeanFlowInvokerAccessImpl2.invokeFlowWithTransaction(BeanFlowInvokerAccessImpl2.java:915)
	jp.ossc.nimbus.service.beancontrol.BeanFlowInvokerAccessImpl2.invokeFlow(BeanFlowInvokerAccessImpl2.java:709)
	sun.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	jp.ossc.nimbus.service.aop.invoker.MethodReflectionCallInvokerService.invoke(MethodReflectionCallInvokerService.java:102)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:231)
	jp.ossc.nimbus.service.aop.interceptor.ExceptionHandlingInterceptorService.invoke(ExceptionHandlingInterceptorService.java:208)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.service.aop.interceptor.BeanFlowMetricsInterceptorService.invoke(BeanFlowMetricsInterceptorService.java:549)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.service.aop.interceptor.MethodJournalInterceptorService.invoke(MethodJournalInterceptorService.java:449)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.service.beancontrol.DefaultBeanFlowInvokerFactoryService$WrappedBeanFlowInvoker.invokeFlow(DefaultBeanFlowInvokerFactoryService.java:1474)
	jp.ossc.nimbus.service.beancontrol.DefaultBeanFlowInvokerFactoryService$WrappedBeanFlowInvoker.invokeFlow(DefaultBeanFlowInvokerFactoryService.java:1461)
	jp.ossc.nimbus.servlet.BeanFlowServlet.processAction(BeanFlowServlet.java:623)
	jp.ossc.nimbus.servlet.BeanFlowServlet.doService(BeanFlowServlet.java:526)
	jp.ossc.nimbus.servlet.BeanFlowServlet.doPost(BeanFlowServlet.java:429)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	jp.ossc.nimbus.servlet.InterceptorChainCallFilter.invoke(InterceptorChainCallFilter.java:275)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:231)
	jp.ossc.nimbus.service.aop.interceptor.servlet.ExceptionHandlingInterceptorService.invokeFilter(ExceptionHandlingInterceptorService.java:209)
	jp.ossc.nimbus.service.aop.interceptor.servlet.ServletFilterInterceptorService.invoke(ServletFilterInterceptorService.java:288)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.service.aop.interceptor.servlet.StreamExchangeInterceptorService.invokeFilter(StreamExchangeInterceptorService.java:916)
	jp.ossc.nimbus.service.aop.interceptor.servlet.ServletFilterInterceptorService.invoke(ServletFilterInterceptorService.java:288)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.service.aop.interceptor.servlet.HttpServletRequestMetricsInterceptorService.invokeFilter(HttpServletRequestMetricsInterceptorService.java:551)
	jp.ossc.nimbus.service.aop.interceptor.servlet.ServletFilterInterceptorService.invoke(ServletFilterInterceptorService.java:288)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.service.aop.interceptor.servlet.BeanFlowSelectCheckInterceptorService.invokeFilter(BeanFlowSelectCheckInterceptorService.java:128)
	jp.ossc.nimbus.service.aop.interceptor.servlet.ServletFilterInterceptorService.invoke(ServletFilterInterceptorService.java:288)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.service.aop.interceptor.servlet.HttpServletRequestCheckInterceptorService.invokeFilter(HttpServletRequestCheckInterceptorService.java:755)
	jp.ossc.nimbus.service.aop.interceptor.servlet.ServletFilterInterceptorService.invoke(ServletFilterInterceptorService.java:288)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.service.aop.interceptor.servlet.ExceptionHandlingInterceptorService.invokeFilter(ExceptionHandlingInterceptorService.java:209)
	jp.ossc.nimbus.service.aop.interceptor.servlet.ServletFilterInterceptorService.invoke(ServletFilterInterceptorService.java:288)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.service.aop.interceptor.servlet.HttpServletResponseDeflateInterceptorService.invokeFilter(HttpServletResponseDeflateInterceptorService.java:219)
	jp.ossc.nimbus.service.aop.interceptor.servlet.ServletFilterInterceptorService.invoke(ServletFilterInterceptorService.java:288)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.service.aop.interceptor.servlet.ServletResponseSetInterceptorService.invokeFilter(ServletResponseSetInterceptorService.java:112)
	jp.ossc.nimbus.service.aop.interceptor.servlet.HttpServletResponseSetInterceptorService.invokeFilter(HttpServletResponseSetInterceptorService.java:204)
	jp.ossc.nimbus.service.aop.interceptor.servlet.ServletFilterInterceptorService.invoke(ServletFilterInterceptorService.java:288)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.service.aop.interceptor.servlet.AccessJournalInterceptorService.invokeFilter(AccessJournalInterceptorService.java:570)
	jp.ossc.nimbus.service.aop.interceptor.servlet.ServletFilterInterceptorService.invoke(ServletFilterInterceptorService.java:288)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.service.aop.interceptor.servlet.ServletRequestInitializeInterceptorService.invokeFilter(ServletRequestInitializeInterceptorService.java:197)
	jp.ossc.nimbus.service.aop.interceptor.servlet.ServletFilterInterceptorService.invoke(ServletFilterInterceptorService.java:288)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.service.aop.interceptor.servlet.ThreadContextInitializeInterceptorService.invokeFilter(ThreadContextInitializeInterceptorService.java:395)
	jp.ossc.nimbus.service.aop.interceptor.servlet.ServletFilterInterceptorService.invoke(ServletFilterInterceptorService.java:288)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.service.aop.interceptor.servlet.SetCharacterEncodingInterceptorService.invokeFilter(SetCharacterEncodingInterceptorService.java:128)
	jp.ossc.nimbus.service.aop.interceptor.servlet.ServletFilterInterceptorService.invoke(ServletFilterInterceptorService.java:288)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.service.aop.interceptor.RequestProcessCheckInterceptorService.invoke(RequestProcessCheckInterceptorService.java:304)
	jp.ossc.nimbus.service.aop.DefaultInterceptorChain.invokeNext(DefaultInterceptorChain.java:203)
	jp.ossc.nimbus.servlet.InterceptorChainCallFilter.doFilter(InterceptorChainCallFilter.java:245)
	org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	org.apache.catalina.filters.CorsFilter.handleSimpleCORS(CorsFilter.java:259)
	org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:163)
	org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
	org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:748)

**Comment by m-takata** [comment]
対応しました。
