### ISSUE TITLE
ThymeleafTemplateEngineService　に Dialect追加用属性を追加して欲しい

### ISSUE THREAD

**Issue by y-kunisaki** [nimbus-org/nimbus#571]
jp.ossc.nimbus.service.template.ThymeleafTemplateEngineService

サービス起動時に
TemplateEngine.addDialect(final IDialect dialect)
にてDialectを設定できるようServiceの属性を追加する必要あり。
複数のDialectを設定する事がある可能性を考慮したIFとして欲しい。

**Comment by m-takata** [comment]
addDialect(IDialect)とaddLinkBuilder(ILinkBuilder)を追加しました。
