### ISSUE TITLE
SCPClientImplでクロスプラットフォームでのSCPが出来ない

### ISSUE THREAD

**Issue by ishidamu** [nimbus-org/nimbus#599]
Windows環境VMからLinux環境へのSCPを行うとエラーが発生する。

**Comment by m-takata** [comment]
WindowsとLinuxのファイルセパレータの違いに起因する問題のようです。

setRemoteFileSeparator(String)を追加しました。

今回の場合だと、この属性で、Linuxのファイルセパレータである'/'を指定してみてください。

また、jp.ossc.nimbus.service.scp.jsch.SCPClientFactoryServiceの実装では、この問題を踏まないようなので、こちらの実装に切り替えることもご検討ください。
