### ISSUE TITLE
テストフレームワークのGUI画面でActionの実行ステータスがわかりにくい

### ISSUE THREAD

**Issue by ishidamu** [nimbus-org/nimbus#77]
シナリオグループ、シナリオ、テストケースの実行中にActionのステータスがわかる仕組みを検討する。

**Comment by m-takata** [comment]
さらに言えば、複数人で、同時に利用する場合に、他の人が使い終わったら、勝手に開始するように開始待ちしたい。

**Comment by ishidamu** [comment]
ついでに、他のユーザがシナリオなどを実行中の場合、そのシナリオの終了後に自動で開始できる仕組みもつくる。

**Comment by ishidamu** [comment]
あーあ、コメントかぶったわ。。。(TдT)

**Comment by ishidamu** [comment]
マージしたので、クローズ。
