### ISSUE TITLE
BeanJSONConverterで特定のJSONからBeanへ変換すると値が正しく設定されない

### ISSUE THREAD

**Issue by ishidamu** [nimbus-org/nimbus#839]
```
[{"Hoge":"1"},{"Hoge":"2"},{"Hoge":"3"}]
```
のようなJSONを下記のようなBeanの配列（TestBean[]）に変換した際に、配列の２個め以降のTestBeanのmHogeが設定されない。
```
public class TestBean{
        private Long mHoge;
        public Long getHoge() {
            return mHoge;
        }
        public void setHoge(Long mHoge) {
            this.mHoge = mHoge;
        }
}
```

**Comment by m-takata** [comment]
jsonの値の型（上記の場合、文字列）とBeanのプロパティの型（上記の場合、Long）が異なり、なおかつ複数回変換が行われた場合（上記の場合、配列であるため）、不具合を踏むようです。

不具合の動作としては、

文字列"1"をHogeプロパティに設定しよう。
setHoge(Long)があるけど、setHoge(String)はない。
じゃぁ、文字列をLongに変換して設定しよう。
Hogeってプロパティは、setHoge(Long)で設定できるな覚えておこう。
設定できた。

文字列"2"をHogeプロパティに設定しよう。
お？Hogeプロパティは、setHoge(Long)で設定できるな。
よし、設定しよう。あれ？型が合わないな。
設定失敗。

という挙動でした。
お？Hogeプロパティは、setHoge(Long)で設定できるなの時に、設定しようとしている値の型とsetterの引数の型をチェックするように修正しました。
