### ISSUE TITLE
DataSetServletRequestParameterConverterのMultipart処理が実行されない。

### ISSUE THREAD

**Issue by y-nakashima0324** [nimbus-org/nimbus#84]
DataSetServletRequestParameterConverterのconvertメソッドの以下は&&が正しいですか？
contentType != null があるので、multipart処理に入らないです。
L355
if(contentType != null || (!contentType.toLowerCase().startsWith(MULTIPART))){
            paramMap = request.getParameterMap();
        }else{

**Comment by m-takata** [comment]
改修終わって、確認までできただろうから、閉じますよ。
