### ISSUE TITLE
クラスター構築時に削除と追加が繰り返される。

### ISSUE THREAD

**Issue by Koyamatsu** [nimbus-org/nimbus#867]
掲題のとおりです。いつ起こるかは不明ですが、クラスターに追加されました⇒削除されましたって繰り返し表示さることがあります。

**Comment by m-takata** [comment]
ログを仕込んで、調査を始めます。

**Comment by m-takata** [comment]
最初のjoinで失敗すると、ハートビートの起点時刻が-1に設定されて、ハートビートチェックの時に、必ずハートビートが途絶えたと判断されて、メンバーから除外される不具合がありました。

修正して、マージしました。
