### ISSUE TITLE
入力ストリームから出力ストリームに書き出すBindingConverterが欲しい

### ISSUE THREAD

**Issue by m-takata** [nimbus-org/nimbus#90]
入力ストリームから読みだして、出力ストリームに書き出すBindingConverterインタフェースの実装クラスが欲しい。

**Comment by m-takata** [comment]
作ったので、確認お願いします。＞ @y-nakashima0324

**Comment by y-nakashima0324** [comment]
期待通りの動作を確認しました。
closeします。
