### ISSUE TITLE
HttpClientFactoryで、HTTP応答ステータスに対して、例外を上げる機能が欲しい

### ISSUE THREAD

**Issue by m-takata** [nimbus-org/nimbus#92]
相手のシステムによって、HTTPの応答ステータスを例外扱い（システムエラー相当）して良い場合がある。
但し、どのステータスが、例外扱いして良いかは、システムにより異なる。
また、URLによって異なる場合もある。
それらを加味したうえで、サービスの定義レベルで、このステータスは、例外扱いにして良い（または、このステータス以外は例外扱いして良い）という設定ができるようにして欲しい。

**Comment by m-takata** [comment]
作ったので、確認お願いします。＞ @y-nakashima0324

**Comment by y-nakashima0324** [comment]
期待通り動作することを確認したのでcloseします。
